#Q1


Label Encoding:
Label encoding assigns a unique numerical label to each category in a categorical variable. The labels are typically integers ranging from 0 to (number of categories - 1).

Ordinal Encoding:
Ordinal encoding assigns numerical values to categories based on their ordinal relationship or hierarchy. It considers the order of the categories and assigns values accordingly.


#Q2

Target Guided Ordinal Encoding is a technique used to encode categorical variables based on their relationship with the target variable. It assigns ordinal values to the categories based on the target variable's mean, median, or some other statistical measure. The purpose is to capture the correlation between the categorical variable and the target variable.

#Q3
Covariance is a measure of the relationship or association between two random variables. It quantifies how changes in one variable correspond to changes in another variable. In statistical analysis, covariance provides insights into the direction and strength of the linear relationship between variables.

Importance of Covariance in Statistical Analysis,Relationship Assessment,Variable Selection,Portfolio Diversification are the features of co variance.
Calculation of Covariance:
The covariance between two variables, X and Y, is calculated using the following formula:

Cov(X, Y) = Σ[(Xᵢ - Ȳ)(Yᵢ - Ȳ)] / (n - 1)

Where:

Xᵢ and Yᵢ represent the individual data points of X and Y, respectively.
Ȳ represents the mean (average) of Y.
Σ denotes the summation of the products of the deviations from the mean.
n represents the number of data points.


In [2]:
#Q4
from sklearn.preprocessing import LabelEncoder
import pandas as pd

data = {
    'Color': ['red', 'green', 'blue', 'red', 'green'],
    'Size': ['small', 'medium', 'large', 'medium', 'small'],
    'Material': ['wood', 'metal', 'plastic', 'plastic', 'metal']
}

df = pd.DataFrame(data)


label_encoder = LabelEncoder()
df_encoded = df.apply(label_encoder.fit_transform)

print(df_encoded)



   Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      2     1         1
4      1     2         0


In [3]:
#Q5
import numpy as np

age = [35, 42, 28, 48, 55]
income = [50000, 60000, 40000, 80000, 90000]
education_level = [3, 4, 2, 4, 5]

data = np.array([age, income, education_level])

covariance_matrix = np.cov(data)

print(covariance_matrix)


[[1.123e+02 2.170e+05 1.180e+01]
 [2.170e+05 4.300e+08 2.200e+04]
 [1.180e+01 2.200e+04 1.300e+00]]


#Q6
Gender: Label Encoding
Education Level: Ordinal Encoding
Employment Status: Label Encoding

It's important to note that the choice of encoding method may depend on the specific characteristics of the dataset, the machine learning algorithm being used, and the desired interpretation of the encoded variables. Additionally, after applying the encoding, it is common practice to one-hot encode the resulting encoded variables before using them in machine learning models to avoid potential bias arising from the numerical values assigned during encoding.

#Q7
